import Navbar from '@/components/Navbar';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200">
      <Navbar />
      <div className="max-w-3xl mx-auto pt-32 pb-20 px-4">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <div className="space-y-6 text-slate-300 leading-relaxed">
          <p>Last updated: {new Date().toLocaleDateString()}</p>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">1. Information We Collect</h2>
            <p>We collect email addresses, organization names, and scan targets that you voluntarily provide when registering or using ShadowSurface. We also store scan results and asset data generated by our platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">2. How We Use Your Data</h2>
            <p>Your data is used solely to provide attack surface scanning services, generate reports, and manage your account. We do not sell or share your data with third parties for marketing purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">3. Data Security</h2>
            <p>We implement industry-standard security measures including encrypted connections, hashed passwords, and access controls. Scan data is stored securely and only accessible to your organization.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">4. Cookies</h2>
            <p>We use minimal cookies for authentication purposes only. No tracking or advertising cookies are used.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">5. Contact</h2>
            <p>For privacy-related questions, contact us at <span className="text-emerald-400">egegoker35@gmail.com</span>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
